package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Echo'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Echo")) {
    expectSteps {
        script {
            name = "variable name"
            scriptContent = "echo %asd%"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            name = "kxe"
            clearConditions()
        }
    }
}
